var vocab = {"vocab": [
["notwendig", "nötig, muss"],
["erarbeiten", "compile, entwickeln"],
["das Gedicht", "poesie"],
["schwach", "ohne Kraft"],
["bedroht", "mit Risiko"],
["erschoßen", "shot"],
["die Währung", "münzen und Geld"],
["beschließen", "auf etwas entscheiden"],
["vermeiden", "avoid"],
["eng", "näh"],
["befürchten", "angst auf etwas haben"],
["furchtbar", "etwas macht angst"],
["die Gleichberechtigung", "equal rights"],
["vielfältig", "Vielfalt - viele Facetten"],
["zögern", "unsicher sein"],
["Aufmerksamkeit", "aufpassen"],
["das Christentum", "Christianity"],
["das Heidentum", "Paganism"],
["eifersüchtig", "jealous"],
["neidisch", "envious"],
["schweigsam", "nicht laut"],
["stumm", "mute"],
["die Stiefeltern", "the step-parents"],
["scheiden", "trennen (z.B. in einer Beziehung)"],
["der See", "a lake (small)"],
["die See", "a sea (big)"],
["der Insasse", "Mitfahrer in einem Fahrzeug"],
["fleißig", "sehr aktiv"],
["zuverlässig", "reliable"],
["treu", "faithful,  not cheating"],
["werwandt", "related"],
["jeden betrügen", "delude/deceive someone"],
["enttäuschen", "to disappoint"],
["schuften", "schwer Arbeit, wie ein Pferd"],
["etwas durch die Blume sagen", "deine Sprache dekorieren (Blume)"],
["die Katze um den heisen Brei", "deine Sprache dekorieren (Katze)"],
["Geld verschwenden", "zuvieles Geld weg geben"],
	["streng sein", "strict, precise, Disziplin"],
	["gleichzeitig", "zusammen passieren"],
	["angemessen", "die Situation passt"],
	["unterhalten", "to keep entertained / amused"],
	["werschwenden", "to disappear"],
	["erledigen", "fertig machen"],
	["das Ergebnis", "the result/outcome"],
	["kurz und bündig", "short and concise"],
	["der Vorsitzende", "der Chef"],
	["der Besitzer", "the owner"],	
	["der Angestellte", "der Mitarbeiter"],
	["die Gewerkschaft", "the union"],
		["die Rente", "the pension (sick, aged)"],
		["die Bewirtung", "the hospitality, provisioning of food"],
		["der Beamter", "public servant"],
		["der Werdegang", "the career"],
		["die Voraussetzung", "the prerequisities"],
		["herum", "around"],
		["die Gleitzeit", "flexibiler Zeitplan"],
		["kiffen", "to smoke weed"],
		["der Dienstwagen", "the company car"],
		["die Frist", "the deadline"],
		["berufsätig", "hat Arbeit"],
		["untersuchen", "investigate"],
		["die Abteilung", "the department or division"],
		["der Absender", "the sender"],
		["der Empfänger", "the receiver"],
			["veraussichtlich", "der Plan in Zükunft"],
			["bevorzugen", "lieblings"],
			["ab|lehnen", "to refuse"],
			["dringend", "sofort"],
			["stätig", "active, in service"],
				["der Mangel", "the deficiency"],
				["die Ernährung", "the nutrition"],
				["kümmern sich an", "to care for"],
				["gelangweilt", "bored"],
				["vereinbaren", "arrange, fix"],
				["die Vorstellung", "the presentation"],
				["reizvoll", "attractive"],
				["nach|denken", "überlegen"],
				["sich auf|regen", "get excited about"],
			["dir Vorschung", "the research"],
				["schwindlich", "dizzy"],
				["der Anlass", "the occasion"],
				["die Stimmung", "the mood"],
				["der Beweis", "the evidence"],
				["ausgezeichnet", "exceptional"],
				["sich bemühen um", "wirklich versuchen"],
					["der Zweifel", "the doubt"],
					["zweifel an etwas", "to have doubts about something"],
					["erhalten", "bekommen (z.B. ein Preis)"],
					["ständig", "permanent, continuous"],
			["der Fortschritt", "the advance, the step forwards"],
				["die Erfindung", "the invention"],
				["scheitern", "to fail"],
				["auffällig", "eye-catching"],
				["oberflächlich", "superficial, shallow"],
				["der Bedarf", "the need"],
				["der Einfluss", "the influence"],
					["das Kennzeichen", "the attribute"],
					["eckig", "angular"],
					["das Rätsel", "the riddle"],
					["einer roten Faden", "a red thread (linking of themes through something - punainen lanka in Finnish)"],
					["zwiefel al", "doubt something"],
					["die Falten", "the wrinkles"],
					["verfassen", "geschrieben"],
					["der Scheinwerfer", "the lighting person"],
					["die Ausstatung", "the fittings, furnishings"],
					["versprechen", "to promise"],
					["der Vortrag", "the presentation"],
					["das Gedächtnis", "the consensus"],
					["die Politik", "the politics"],
					["blasse", "pale"],
					["sterben an etwas", "(dativ) to die of something"],
					["das Tal", "the valley"],
					["anstecken", "to spread, infect, catch fire"],
					["jungendlich", "teenage"],
					["sich gegenseitig ärgern", "to annoy each other"],
					["ehrenamtlich/freiwillig", "arbeit ohne Geld, donation"],
					["die Armut", "the poor"],
					["der Reichtum", "the rich"],
					["die Nachhilfestunden", "extra private teaching"],
					["betteln", "to beg"],
					["die Ausbildung", "Azubi, TAFE education"],
						["die Bildung", "the learning"],
						["gebildet", "learned, viele Büche gelesen"],
						["eingebildet", "arrogant"],
						["etwas schätzen", "to treasure or value something"],
						["die Gemeinshaft", "the society"],
						["die Fairness", "the fairness"],
						["ich wäre", "I would be"],
						["bedürftig", "in need"],
						["das Bedürfnis", "the want"],
						["der Bedarf", "the need"],
						["kontrollieren", "prüfen, to check"],
						["der Stau", "the traffic jam"],
						["die Gebühr", "the cost (entry, etc.)"],
						["der Plattenbau", "Boxy cement apartments"],
						["bestechen (akk.)", "to bribe"],
						["zwar", "indeed"],
						["entsorgen", "dispose"],
			["sorgen", "to care, worry"],
	["der Betrener", "the carer (i.e. for kids)"],
	["innerhalb/außerhalb (gen.)", "inside of / outside of"],
	["der Besitzer", "the owner"],
	["das Gedränge", "the crowd"],
	["die Nachhaltigkeit", "reusability, sustainability"],
	["die Dose", "the box, Tupperware"],
	["herstellen", "produzieren"],
	["raten", "guess"],
	["erraten", "guess"],
	["nicht nur... sondern ...", "not only ... but also ..."],
	["sich bewerben um", "to apply for"],
	["die Schublade", "the drawer"],
	["die Dürren", "the drought"],
	["wiederwerwerten", "to reczcle"],
	["das Ziel", "der Plan"],
	["absichtlich", "intentionally, deliberately"],
			["deren / dessen", "whose (fem. + pl.) / whose (mas. + neut.)"],
			["die Abgase", "the exhaust"],
				["der Stadtrand", "the suburbs"],
				["spannend", "exciting"],
				["keiner", "keiner Mensch"],
				["Viele Grüße", "neutral ending of letter"],
				["üblich", "normal"],
				["rasen", "to race / go fast"],
				["jemand beleiden", "to insult someone"],
			["einheimisch", "indigenous"],
			["ansprechen", "begin to speak, start conversation"],
				["höchstwahrscheinlich", "almost certainly"],
				["wohl", "60% sicher"],
				["zurück|legen", "how far travelled, eg. km"],
				["sich verlaufen", "to get lost"],
				["sich verhören", "to mishear"],
				["sich verlesen", "to misread"],
				["das Zinsen", "the bank interest"],
				["abheben", "to withdraw"],
				["beantragen", "to apply for"],
				["der Verlust", "the loss"],
				["der Antrag", "the application form"],
				["der Wohlstand", "the wealth"],
				["das Verbrechen", "the crime"],
				["eingeschappt", "no longer talking"]
]
}